@startuml
'https://plantuml.com/sequence-diagram

class "App" as App {
    __Methods__
    +main(String[] args)
    +start(Stage primaryStage)
    __Attributes__
    Displays visual information and handles visual events
}

class "fileSaveLoad" as fileSaveLoad {
    __Methods__
    +saveList()
    +saveLists()
    +loadList()
    +loadLists()
    __Attributes__
    Saves/Loads items and lists to/from external storage
}

class "TDItemEdit" as TDItemEdit {
    __Methods__
    +addTDItem(TDList ToDoList)
    +removeTDItem(TDList ToDoList, TDItem removed)
    +editDescription(TDItem Item, String newDesc)
    +editDate(TDItem Item, String newDate)
    +editComplete(TDItem Item, Boolean newComplete)
    __Attributes__
    Adds/deletes items to/from a list
    Edits attributes of an item in a list
}

class "TDListDisplay" as TDListDisplay {
    __Methods__
    +displayIncomplete(TDList list)
    +displayComplete(TDList list)
    __Attributes__
    Displays a to-do list
}

class "TDListEdit" as TDListEdit {
    __Methods__
    +addTDList(ArrayList<TDList> TDLists)
    +removeTDList(ArrayList<TDList> TDLists, TDList removed)
    +editTitle(TDList ToDoList)
    __Attributes__
    Adds/removes TDList from memory
    Edits title of a to-do list
}

object TDItem {
    __Methods__
    --Simple Getters--
    +getDesc()
    +getDate()
    +getComplete()
    --Simple Setters--
    +setDesc(String newDesc)
    +setDate(String newDate)
    +setComplete(Boolean newComplete)
    __Attributes__
    Each object is intended to be held within a greater list, holds a description, date, and completion mark
}

object TDList {
    __Methods__
    --Simple Getters--
    +getTDItems()
    +getTile()
    --Simple Setters--
    +setTDItems(ArrayList<TDItem> newList)
    +setTitle (String newTitle)
    __Attributes__
    To-Do list - holds Items to do and a title
}

App -right-> "fileSaveLoad" : Saves or Loads file with
App --> "TDItemEdit" : Edits items within a to-do list
App-left->"TDListDisplay" : Displays a given list
App -up-> "TDListEdit" : Edits a given list
TDList -- TDItem : holds


@enduml